{% set name = "welltestpy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e9d49d8716813bd123a25a742992ce8ed0222ed7e4fba7a3f4798a12e05a417

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=3.5
  run:
    - python >=3.6
    - anaflow >=1.0.0, <2.0
    - numpy >=1.14.5, <2.0
    - scipy >=1.1.0, <2.0
    - spotpy >=1.5.0, <2.0
    - matplotlib-base

test:
  imports:
    - welltestpy
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/welltestpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: welltestpy - package to handle well-based Field-campaigns.
  doc_url: https://welltestpy.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/welltestpy

extra:
  recipe-maintainers:
    - MuellerSeb
