{% set name = "welltestpy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2182ef49db042531c82319a66014819210d9886fd695b81e0b22196b314f8ced

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.8.0
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - packaging >=20
    - anaflow >=1.0.0
    - numpy >=1.14.5
    - scipy >=1.1.0
    - spotpy >=1.5.0
    - matplotlib-base

test:
  imports:
    - welltestpy
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/welltestpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: welltestpy - package to handle well-based Field-campaigns.
  doc_url: https://welltestpy.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/welltestpy

extra:
  recipe-maintainers:
    - MuellerSeb
